apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml
patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          ingress-ready: "true"
          kubernetes.io/os: linux
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
